<?php
require_once "Database.php";

class City extends Database
{
    public function __construct()
    {
        parent::__construct();

        $this->table = "city";
    }

    public function get($query): array
    {
        return parent::get($query); // TODO: Change the autogenerated stub
    }

    public function find($column): array|bool|object
    {
        return parent::find($column); // TODO: Change the autogenerated stub
    }

    public function getByProvince($query, $province) : object | null | array {
        $query = "SELECT {$query} FROM {$this->table} WHERE province_id = :province_id";
        $select = $this->connection->prepare($query);
        $select->bindParam(":province_id", $province, PDO::PARAM_INT);
        $select->execute();

        $data = [];

        while ($row = $select->fetch(PDO::FETCH_ASSOC)) {
            $data[] = (object) $row;
        }
        return $data;
    }
}