<?php
require_once "Database.php";

class Province extends Database
{
    public function __construct()
    {
        parent::__construct();

        $this->table = "province";
    }

    public function get($query): array
    {
        return parent::get($query); // TODO: Change the autogenerated stub
    }

    public function find($column): array|bool|object
    {
        return parent::find($column); // TODO: Change the autogenerated stub
    }
}