<?php
require_once "Database.php";;

class Users extends Database
{
    public function __construct()
    {
        parent::__construct();

        $this->table = "users";
    }

    public final function get($query) : array
    {
        return parent::get($query); // TODO: Change the autogenerated stub
    }

    public final function find($column) : array | bool | object
    {
        return parent::find($column); // TODO: Change the autogenerated stub
    }

    public final function insert($data) : string | bool
    {
        return parent::insert($data); // TODO: Change the autogenerated stub
    }

    public final function update($where, $data) : bool | string {
        return parent::update($where, $data);
    }

    public final function delete($where) : bool
    {
        return parent::delete($where); // TODO: Change the autogenerated stub
    }

    public final function checkLogin() : void {
        if ($this->isLogin() == false) {
            header("Location: login.php");
            exit();
        }

    }

    public final function isLogin() : bool {
        if (isset($_SESSION["userInfo"])) {
            if ($_SESSION["userInfo"]["isLogin"] == true) {
                $userId = $_SESSION["userInfo"]["userId"];
                $email = $_SESSION["userInfo"]["email"];
                $mobile = $_SESSION["userInfo"]["mobile"];
                $password = $_SESSION["userInfo"]["password"];

                $userInfo = $this->find(array("id", $userId));

                if ($userInfo->email != $email || $userInfo->password != $password || $userInfo->status != '1') {
                    return false;
                } else {
                    return true;
                }

            } else {
                return false;
            }

        } else {
            return false;
        }

    }


}