<?php
require_once "Database.php";;

class Users extends Database
{
    public function __construct()
    {
        parent::__construct();

        $this->table = "users";
    }

    public function get($query)
    {
        return parent::get($query); // TODO: Change the autogenerated stub
    }

    public function find($column) {
        return parent::find($column);
    }

    public function insert($data)
    {
        return parent::insert($data); // TODO: Change the autogenerated stub
    }

    public function delete($where)
    {
        return parent::delete($where); // TODO: Change the autogenerated stub
    }


}