<?php
require_once "Database.php";;

class Users extends Database
{
    public function __construct()
    {
        parent::__construct();

        $this->table = "users";
    }

    public final function get($query) : array
    {
        return parent::get($query); // TODO: Change the autogenerated stub
    }

    public final function find($column) : array | bool
    {
        return parent::find($column); // TODO: Change the autogenerated stub
    }

    public final function insert($data) : string | bool
    {
        return parent::insert($data); // TODO: Change the autogenerated stub
    }

    public final function delete($where) : bool
    {
        return parent::delete($where); // TODO: Change the autogenerated stub
    }


}